# Generated by Django 3.2 on 2023-09-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
