# Generated by Django 3.2 on 2023-09-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logid', models.IntegerField()),
                ('moneyTimes100', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
