# Generated by Django 3.2 on 2023-09-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='paidmoneyTimes100',
            field=models.TimeField(default=0),
        ),
    ]
