# Generated by Django 3.2 on 2023-09-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230924_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('userid', 'wx_openid')},
        ),
    ]
