# Generated by Django 3.2 on 2023-09-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230924_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
