# Generated by Django 3.2 on 2023-12-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_warrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
