# Generated by Django 3.2 on 2023-12-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20231206_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
