# Generated by Django 3.2 on 2024-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_runner_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='userid',
        ),
        migrations.AlterField(
            model_name='runner',
            name='status',
            field=models.CharField(max_length=128),
        ),
    ]
