# Generated by Django 3.2 on 2024-01-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='more',
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='paidtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='whofinished',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
