# Generated by Django 3.2 on 2024-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20240122_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='paidmoneyTimes100',
            field=models.IntegerField(default=0),
        ),
    ]
