# Generated by Django 3.2 on 2024-01-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_log_paidmoneytimes100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='paidtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
