# Generated by Django 3.2 on 2024-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_log_paidtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='whofinished',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
