# Generated by Django 3.2 on 2024-01-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_money_friendname'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='notes',
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
    ]
