# Generated by Django 3.2 on 2024-01-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_log_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='department',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
