# Generated by Django 3.2 on 2024-01-23 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_log_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='wantTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
