# Generated by Django 3.2 on 2024-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_log_wanttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='transactionId',
            field=models.CharField(default='s', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='treadNum',
            field=models.CharField(default='s', max_length=32),
            preserve_default=False,
        ),
    ]
