# Generated by Django 3.2 on 2024-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20240124_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='using',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
