# Generated by Django 3.2 on 2024-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_friend_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='more',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
