# Generated by Django 3.2 on 2024-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_user_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='hospitalCustom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
