// index.js
Page({
    data: {
        hospitalList: [{
            img: '/images/img/hospital01.jpg',
            name: '北京医院',
            rank: '三甲',
            type: '综合医院',
            description: '重点科室: 医院设又国家级重点学科9个，并且有2.2e7个床位，足够容纳所有北京人'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '这是一个名字非常长的医院这是一个名字非常长的医院这是一个名字非常长的医院这是一个名字非常长的医院',
            rank: '三甲',
            type: '综合医院',
            description: '简介02'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院03',
            rank: '三甲',
            type: '综合医院',
            description: '简介03'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院04',
            rank: '三甲',
            type: '综合医院',
            description: '简介04'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院05',
            rank: '三甲',
            type: '综合医院',
            description: '简介05'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院06',
            rank: '三甲',
            type: '综合医院',
            description: '简介06'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院07',
            rank: '三甲',
            type: '综合医院',
            description: '简介07'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院08',
            rank: '三甲',
            type: '综合医院',
            description: '简介08'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院09',
            rank: '三甲',
            type: '综合医院',
            description: '简介09'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院10',
            rank: '三甲',
            type: '综合医院',
            description: '简介10'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院11',
            rank: '三甲',
            type: '综合医院',
            description: '简介11'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院12',
            rank: '三甲',
            type: '综合医院',
            description: '简介12'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院13',
            rank: '三甲',
            type: '综合医院',
            description: '简介13'
        }, {
            img: '/images/img/hospital01.jpg',
            name: '医院14',
            rank: '三甲',
            type: '综合医院',
            description: '简介14'
        }]
    }
})